# Generated by Django 5.0.1 on 2024-03-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_engagement', '0002_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Password',
            field=models.CharField(default='admin123', max_length=15),
        ),
    ]
