# Generated by Django 5.0.1 on 2024-03-22 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_engagement', '0003_alter_user_data_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='Phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_data',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
