# Generated by Django 5.0.1 on 2024-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_engagement', '0004_user_data_email_user_data_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
