# Generated by Django 5.0.1 on 2024-04-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_engagement', '0005_alter_user_data_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Profilepic',
            field=models.ImageField(blank=True, default='default_male_pic.png', null=True, upload_to='profile_pics/'),
        ),
    ]
