# Generated by Django 5.0.1 on 2024-04-19 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_engagement', '0006_alter_user_data_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='Address',
            new_name='Address1',
        ),
        migrations.AddField(
            model_name='user_data',
            name='Address2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
