# Generated by Django 5.0.1 on 2024-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_engagement', '0008_event_timesheetdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdata',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetdata',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetdata',
            name='total_time',
            field=models.CharField(default='', max_length=8),
        ),
    ]
