# Generated by Django 4.2.7 on 2024-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_engagement', '0012_alter_user_data_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('holidayid', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('day', models.CharField(max_length=15)),
            ],
        ),
    ]
