# Generated by Django 4.2.7 on 2024-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_engagement', '0014_alter_holidays_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('leave_id', models.CharField(max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Pending', max_length=20)),
            ],
        ),
    ]
